{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation",
    "module": "impl",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.ricky.enavigation",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "impl-1.0.0.aar",
          "url": "impl-1.0.0.aar",
          "size": 93439,
          "sha512": "001071a7ca53b1092513f149e749e42dd94bad9c9e5cf115f408942026f55359c384f485b47bfd9dde893208ebe40c81aedfe2a817e61432264ea4346d35bf77",
          "sha256": "38bf7db4012231a11958f0f566deee325930a773914f7e81655bf4dabbf686bd",
          "sha1": "7deb8db292bba5f1e93568e3ac812bc31fb81ac9",
          "md5": "639fa6c95deccd5b8af5c4096b02d02d"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.ricky.enavigation",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "impl-1.0.0.aar",
          "url": "impl-1.0.0.aar",
          "size": 93439,
          "sha512": "001071a7ca53b1092513f149e749e42dd94bad9c9e5cf115f408942026f55359c384f485b47bfd9dde893208ebe40c81aedfe2a817e61432264ea4346d35bf77",
          "sha256": "38bf7db4012231a11958f0f566deee325930a773914f7e81655bf4dabbf686bd",
          "sha1": "7deb8db292bba5f1e93568e3ac812bc31fb81ac9",
          "md5": "639fa6c95deccd5b8af5c4096b02d02d"
        }
      ]
    }
  ]
}
