{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation",
    "module": "impl",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.ricky.enavigation",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "impl-1.0.0.aar",
          "url": "impl-1.0.0.aar",
          "size": 96055,
          "sha512": "a577cbdfe0966a183eac88bcc9471e1606df8aee9424dbc2d80038fe1937514ebf86a29891b7d24e8159ee1ddef577d5fbbbd71f82c8651d1dcea473faced5fd",
          "sha256": "e09c3cdaa190b771b3148f0716b624341658d1d008184fb4c047d32593bfa520",
          "sha1": "b8c750c85469ad8fc965eddc893666b541ea1285",
          "md5": "5deecde2502e98af465164744588915b"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.ricky.enavigation",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "impl-1.0.0.aar",
          "url": "impl-1.0.0.aar",
          "size": 96055,
          "sha512": "a577cbdfe0966a183eac88bcc9471e1606df8aee9424dbc2d80038fe1937514ebf86a29891b7d24e8159ee1ddef577d5fbbbd71f82c8651d1dcea473faced5fd",
          "sha256": "e09c3cdaa190b771b3148f0716b624341658d1d008184fb4c047d32593bfa520",
          "sha1": "b8c750c85469ad8fc965eddc893666b541ea1285",
          "md5": "5deecde2502e98af465164744588915b"
        }
      ]
    }
  ]
}
