{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation",
    "module": "impl",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.ricky.enavigation",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "impl-1.0.0.aar",
          "url": "impl-1.0.0.aar",
          "size": 96135,
          "sha512": "2167934ef4cea9e7a46dcac2ca7a0b9e4def2039b4203766e9cdef7e7c85808ef598d2249baf5642e7826b37ed54e2dd5cfb2d3d37b294e7f78b45e17c8f4fad",
          "sha256": "ba1c51dfcef79e786ba7481987a77e75208d58cdedcba3b48e620bc7d4bf49bc",
          "sha1": "35ce0c8f593712582a7dcb3bcee5a055803a2f3b",
          "md5": "5acf0799f78db495b1a9aae10a41813a"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.ricky.enavigation",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "impl-1.0.0.aar",
          "url": "impl-1.0.0.aar",
          "size": 96135,
          "sha512": "2167934ef4cea9e7a46dcac2ca7a0b9e4def2039b4203766e9cdef7e7c85808ef598d2249baf5642e7826b37ed54e2dd5cfb2d3d37b294e7f78b45e17c8f4fad",
          "sha256": "ba1c51dfcef79e786ba7481987a77e75208d58cdedcba3b48e620bc7d4bf49bc",
          "sha1": "35ce0c8f593712582a7dcb3bcee5a055803a2f3b",
          "md5": "5acf0799f78db495b1a9aae10a41813a"
        }
      ]
    }
  ]
}
