{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation.plugin",
    "module": "ENavigationPlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "ENavigationPlugin-1.0.0.jar",
          "url": "ENavigationPlugin-1.0.0.jar",
          "size": 12657,
          "sha512": "76e664d05a3e8e3ea3464a7c35879103ba985e8f1e7dc6069ccf5b855919c11b986f1a1107ff064b6acdfd7d5016a1399693ee955ee907f83ed878a16294dabd",
          "sha256": "94d277cc5dfa898d8672e38abfc59c3c0e5b4a4e13981853db63244a83fd03b9",
          "sha1": "e9d07b93e1495e4c0a6ff2732edbea57b33c9582",
          "md5": "be27946d2a46fbe488b095c154d460a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "ENavigationPlugin-1.0.0.jar",
          "url": "ENavigationPlugin-1.0.0.jar",
          "size": 12657,
          "sha512": "76e664d05a3e8e3ea3464a7c35879103ba985e8f1e7dc6069ccf5b855919c11b986f1a1107ff064b6acdfd7d5016a1399693ee955ee907f83ed878a16294dabd",
          "sha256": "94d277cc5dfa898d8672e38abfc59c3c0e5b4a4e13981853db63244a83fd03b9",
          "sha1": "e9d07b93e1495e4c0a6ff2732edbea57b33c9582",
          "md5": "be27946d2a46fbe488b095c154d460a1"
        }
      ]
    }
  ]
}
