{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation",
    "module": "complier",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.ricky.enavigation",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "complier-1.0.0.jar",
          "url": "complier-1.0.0.jar",
          "size": 20972,
          "sha512": "63cef6608bcb8f308937396854e6cb71916892f5a7e82b76cf7a2ecdde7a550c51d2643f2c40cec487fe4394108ec6ba3e37beef85255e41a802ce15b21293b8",
          "sha256": "3102b8c02087c24a1d8a42cdd518b9622ca0ec337d3fbf7db3e7abbd9176384d",
          "sha1": "0563bf2b3d10f84a68460435917762411fa56842",
          "md5": "9fb53037e5599f10617b3ad217c32916"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.ricky.enavigation",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "complier-1.0.0.jar",
          "url": "complier-1.0.0.jar",
          "size": 20972,
          "sha512": "63cef6608bcb8f308937396854e6cb71916892f5a7e82b76cf7a2ecdde7a550c51d2643f2c40cec487fe4394108ec6ba3e37beef85255e41a802ce15b21293b8",
          "sha256": "3102b8c02087c24a1d8a42cdd518b9622ca0ec337d3fbf7db3e7abbd9176384d",
          "sha1": "0563bf2b3d10f84a68460435917762411fa56842",
          "md5": "9fb53037e5599f10617b3ad217c32916"
        }
      ]
    }
  ]
}
