{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation",
    "module": "complier",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.ricky.enavigation",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "complier-1.0.0.jar",
          "url": "complier-1.0.0.jar",
          "size": 20987,
          "sha512": "195ca955e4590a1fc405e179a334c1457b43afeb57fea4539bf3ab699c1fac3f66e0136f75e6947663da283051a6e2d2d6f231993ecaf5765c0462148d5cae23",
          "sha256": "7af853f8daaf8a17c8937e7700542f9569a4502443916d79428da776041c5aec",
          "sha1": "8b2a703e8cd59a1972264199ba2dd5ae01a63cca",
          "md5": "2e53b9440ebe5ac53cdf7627081a24ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.ricky.enavigation",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "complier-1.0.0.jar",
          "url": "complier-1.0.0.jar",
          "size": 20987,
          "sha512": "195ca955e4590a1fc405e179a334c1457b43afeb57fea4539bf3ab699c1fac3f66e0136f75e6947663da283051a6e2d2d6f231993ecaf5765c0462148d5cae23",
          "sha256": "7af853f8daaf8a17c8937e7700542f9569a4502443916d79428da776041c5aec",
          "sha1": "8b2a703e8cd59a1972264199ba2dd5ae01a63cca",
          "md5": "2e53b9440ebe5ac53cdf7627081a24ad"
        }
      ]
    }
  ]
}
