{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation",
    "module": "complier",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.ricky.enavigation",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "complier-1.0.0.jar",
          "url": "complier-1.0.0.jar",
          "size": 20972,
          "sha512": "780b7625364b584245909bd089c6bbc76c3558083d4900ff4d3317104200bc2ffbaa24056e1939b912e63f968b277a5a147009b6615402b448bb3ccb619b4d24",
          "sha256": "716edf0f397badba83b134d0eadcb2e26e562ff7d145e96f8c77edd7eeba50ea",
          "sha1": "b0468f00a2031d6ddeac0b56e29c9a90d8a603ab",
          "md5": "f529baebc68b3fd9f09420f6dfb7efd9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.ricky.enavigation",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "complier-1.0.0.jar",
          "url": "complier-1.0.0.jar",
          "size": 20972,
          "sha512": "780b7625364b584245909bd089c6bbc76c3558083d4900ff4d3317104200bc2ffbaa24056e1939b912e63f968b277a5a147009b6615402b448bb3ccb619b4d24",
          "sha256": "716edf0f397badba83b134d0eadcb2e26e562ff7d145e96f8c77edd7eeba50ea",
          "sha1": "b0468f00a2031d6ddeac0b56e29c9a90d8a603ab",
          "md5": "f529baebc68b3fd9f09420f6dfb7efd9"
        }
      ]
    }
  ]
}
