{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation",
    "module": "api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.jar",
          "url": "api-1.0.0.jar",
          "size": 3315,
          "sha512": "68e19c2ca1ace95bd857439de3fa548a3f239b10c3c7229b9632553dff5531c6ea51f0bffe58643233b63a7f8320358f2c607e894bb6da4d5f7d9e3f639a64a4",
          "sha256": "916b9ce1bfcabc6e994c47954112c7e4e0abed5899c67550559d991208f2f0f9",
          "sha1": "ff78404bd1849ce0a0fcf036d86f298eddb12d7c",
          "md5": "b5096b6906d7687b8b738f0b284bbdb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.jar",
          "url": "api-1.0.0.jar",
          "size": 3315,
          "sha512": "68e19c2ca1ace95bd857439de3fa548a3f239b10c3c7229b9632553dff5531c6ea51f0bffe58643233b63a7f8320358f2c607e894bb6da4d5f7d9e3f639a64a4",
          "sha256": "916b9ce1bfcabc6e994c47954112c7e4e0abed5899c67550559d991208f2f0f9",
          "sha1": "ff78404bd1849ce0a0fcf036d86f298eddb12d7c",
          "md5": "b5096b6906d7687b8b738f0b284bbdb4"
        }
      ]
    }
  ]
}
