{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation",
    "module": "api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.jar",
          "url": "api-1.0.0.jar",
          "size": 3315,
          "sha512": "28de7e88685432233b0497f4cd99ca14793b77fad9b5566c499b06d167ccae42e4b4f0b5a32062a7d6f611f58d81f4469d23a49e5ca619c204b5bf7499d0f878",
          "sha256": "043e4e840410ffe7707b0ab1701da040bf03fb2b714292cadf229df80aeb0ff4",
          "sha1": "74931a52a102a3f17c0f9e2d150e82f80c6acb37",
          "md5": "363c2038ff96d8cce4125e081eaac215"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.jar",
          "url": "api-1.0.0.jar",
          "size": 3315,
          "sha512": "28de7e88685432233b0497f4cd99ca14793b77fad9b5566c499b06d167ccae42e4b4f0b5a32062a7d6f611f58d81f4469d23a49e5ca619c204b5bf7499d0f878",
          "sha256": "043e4e840410ffe7707b0ab1701da040bf03fb2b714292cadf229df80aeb0ff4",
          "sha1": "74931a52a102a3f17c0f9e2d150e82f80c6acb37",
          "md5": "363c2038ff96d8cce4125e081eaac215"
        }
      ]
    }
  ]
}
