{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation",
    "module": "api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.jar",
          "url": "api-1.0.0.jar",
          "size": 3315,
          "sha512": "bec20737b0a733021bacbf400504622b48fea158b1ad8c03237a42d722d43e2860cf8cda9097b47a923b1c655a954c5343792a507b194c562ebb43f543a58a67",
          "sha256": "0d9efff6b923081662904bbacf9ad0c1d6b18d7d805d9da3a01eda609ca0aaff",
          "sha1": "b037fb964e419cdc430f97462b83b3e5e687a3b3",
          "md5": "17e4b97b3125f007e8731c269ec832ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.jar",
          "url": "api-1.0.0.jar",
          "size": 3315,
          "sha512": "bec20737b0a733021bacbf400504622b48fea158b1ad8c03237a42d722d43e2860cf8cda9097b47a923b1c655a954c5343792a507b194c562ebb43f543a58a67",
          "sha256": "0d9efff6b923081662904bbacf9ad0c1d6b18d7d805d9da3a01eda609ca0aaff",
          "sha1": "b037fb964e419cdc430f97462b83b3e5e687a3b3",
          "md5": "17e4b97b3125f007e8731c269ec832ab"
        }
      ]
    }
  ]
}
