{
  "formatVersion": "1.1",
  "component": {
    "group": "ENavigation",
    "module": "enavigation_plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "enavigation_plugin-unspecified.jar",
          "url": "enavigation_plugin-unspecified.jar",
          "size": 4609,
          "sha512": "e13192f83c24d9283f73986e57a022176214d1c0e2e77381e756643060a030ced8ecfa37c2b0ae4aaba258ad4ff971428e00778dc84a49d2b74aa9e5f8656ea5",
          "sha256": "e31a39a17b92ae67861b9079aed63ee439824b4652419e4cdeca0aea09bc119c",
          "sha1": "67c1874832429676e5e85893b20883067e592b6d",
          "md5": "ac2c9378613318c9eb8b81288a926709"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "enavigation_plugin-unspecified.jar",
          "url": "enavigation_plugin-unspecified.jar",
          "size": 4609,
          "sha512": "e13192f83c24d9283f73986e57a022176214d1c0e2e77381e756643060a030ced8ecfa37c2b0ae4aaba258ad4ff971428e00778dc84a49d2b74aa9e5f8656ea5",
          "sha256": "e31a39a17b92ae67861b9079aed63ee439824b4652419e4cdeca0aea09bc119c",
          "sha1": "67c1874832429676e5e85893b20883067e592b6d",
          "md5": "ac2c9378613318c9eb8b81288a926709"
        }
      ]
    }
  ]
}
