{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 12606,
          "sha512": "91e1f1a2fcde97595a8f0d8498ca5d5f86d0eed6e39af7b96a9ed9070a381a02d5a5bf17cd8ba6a41dfefbfb544e1a2e974671d001fe7ff44067c93b1a66bdd1",
          "sha256": "53d05649a427a02fe76a5d5acaa8df4d7515477685ebd1ca52fab13b753c9438",
          "sha1": "9f090c1d69cc11ca336c3ef5c87ca8d4e5481567",
          "md5": "fa7e21816e2094951798d56ff1b0d993"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 12606,
          "sha512": "91e1f1a2fcde97595a8f0d8498ca5d5f86d0eed6e39af7b96a9ed9070a381a02d5a5bf17cd8ba6a41dfefbfb544e1a2e974671d001fe7ff44067c93b1a66bdd1",
          "sha256": "53d05649a427a02fe76a5d5acaa8df4d7515477685ebd1ca52fab13b753c9438",
          "sha1": "9f090c1d69cc11ca336c3ef5c87ca8d4e5481567",
          "md5": "fa7e21816e2094951798d56ff1b0d993"
        }
      ]
    }
  ]
}
