{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 12606,
          "sha512": "abbb49474bbb8a88926b62bb2ed2fafa1bde0d6a87f1fed3e60b57c88954e1a50b57dac4f5cb87d96cdd380239fc4d2cf5960493e7bb1bd08781e5c25891308e",
          "sha256": "c64e1ecac7a834e694dda98164e7809b03fdd30df65f9b06782c115af3e9e2ad",
          "sha1": "8f7f9b0d4bb14246e63892e59c4832b881f62160",
          "md5": "932f1137f8250c738f3fe249901ac911"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 12606,
          "sha512": "abbb49474bbb8a88926b62bb2ed2fafa1bde0d6a87f1fed3e60b57c88954e1a50b57dac4f5cb87d96cdd380239fc4d2cf5960493e7bb1bd08781e5c25891308e",
          "sha256": "c64e1ecac7a834e694dda98164e7809b03fdd30df65f9b06782c115af3e9e2ad",
          "sha1": "8f7f9b0d4bb14246e63892e59c4832b881f62160",
          "md5": "932f1137f8250c738f3fe249901ac911"
        }
      ]
    }
  ]
}
