{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ricky.enavigation",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 12606,
          "sha512": "5d778794332da8f75c636baef512dfb2fc5db6d014f2f984cd8eabd28e74df0cbf3a3b4ab1f90d0ea99bd6b59c3bf68f04dc916bd899b05c29d1e014938c85e6",
          "sha256": "45f5989d2e5907110b0f48ac9fcbdd620c65da092cc95453316001c0ed0326b4",
          "sha1": "8e2b74f78907ad50f586acada97d5fa705070e92",
          "md5": "b5e5f5a6135240cdd354ce838814e988"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 12606,
          "sha512": "5d778794332da8f75c636baef512dfb2fc5db6d014f2f984cd8eabd28e74df0cbf3a3b4ab1f90d0ea99bd6b59c3bf68f04dc916bd899b05c29d1e014938c85e6",
          "sha256": "45f5989d2e5907110b0f48ac9fcbdd620c65da092cc95453316001c0ed0326b4",
          "sha1": "8e2b74f78907ad50f586acada97d5fa705070e92",
          "md5": "b5e5f5a6135240cdd354ce838814e988"
        }
      ]
    }
  ]
}
